version: '3.1'

services:

  db:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"

  go:
    image: go
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "1-bullseye"
        NODE_VERSION: "lts/*"
    environment:
      DBUSER: root
      DBPASS: example
    volumes:
      - ..:/workspace:cached
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: /bin/sh -c "while sleep 1000; do :; done"
    restart: always